### PR TITLE
Fixed osx -> osx_64 platform name

### PR DESCRIPTION
**Pull request by oleksandr-torosh**

### CODE REVIEW

**Comment by ArekSredzki** [comment]
@oleksandr-torosh either works in this case, and seeing as osx does not have 32 bit, the `_64` is redundant.

**Comment by ArekSredzki** [comment]
Thank you for the contribution, but I'm not inclined to merge this one in

**Comment by oleksandr-torosh** [comment]
There are some issue.
http://download.domain.com/download/osx - you will be redirected to /home page.
But it works with http://download.domain.com/download/osx_64
But it doesn't work with http://download.domain.com/download/latest/osx_64

**Comment by oleksandr-torosh** [comment]
Created issue https://github.com/ArekSredzki/electron-release-server/issues/31

**Comment by gazzer82** [comment]
Hmmm, but how do i access the releases from the GUI when it detects my platform as OS X all the time, therefor telling me there are no builds available for my platform? I can manually download the release using the links above, but that's not the same thing?

**Comment by ArekSredzki** [comment]
You can see all platform releases if you click the show more link

**Comment by gazzer82** [comment]
If you look at the attached screenshots you can see that there is a valid upload for OSX_64, but when i go to the show more link it only shows me the window release, and no link to the OSX_64 download?

screen shot 2016-07-12 at 16 06 02
screen shot 2016-07-12 at 16 05 47

**Comment by ArekSredzki** [comment]
@gazzer82 `.zip` OS X uploads are only used for updating.  You'll need to upload the `.dmg` generated by `electron-builder` in order to let people to install the app :)

**Comment by gazzer82** [comment]
Yes sorry, worked that our in the end, doh!

**Pull request closed without merging**
