### PR TITLE
Proposal to provide NSIS auto-update feature

### PR DESCRIPTION
**Pull request by jmvallejo**
- Added routes for latest.yml in order to support NSIS auto-update. 
- Added VersionController.nsis action. 
- Added sha256 hash generation for .exe files.

### CODE REVIEW

**Comment by johanwilson** [comment]
Very good, but the releases 17.0.0 of electron-builder has some breaking [changes](https://github.com/electron-userland/electron-builder/releases/tag/v17.0.0).

**Comment by jmvallejo** [comment]
I'm not sure that it's an issue here as the .yml file is being generated on the server. If a client has an alpha/beta version, will the updater package look for alpha.yml/beta.yml instead? If so I think I could make it work by adding a couple different routes.

**Comment by kbala** [comment]
I tested this PR, It downloads the latest exe. But its again we have to install app manually with latest exe :(

**Comment by wontem** [comment]
What status of PR? I have add some updates on top of it:
https://github.com/wontem/electron-release-server/commit/75d03bb08ae1d605fd572c97dcc3b332ec2594e1
and want to know your opinion about it.

**Comment by lazlojuly** [comment]
@jmvallejo this is good stuff. But I can't help but wonder if maybe both options should be possible:

1. Generate the yml files - your PR
2. Upload yml files with along with the app files (zip, dmg, exe etc.)

Should be able to configure electron-release-server to expect yml files or to generate them on the fly.

Also related is the Staged Rollouts feature of electron-builder's electron-updater where the percentage is also defined in the latest.yml files. Once electron-release-server supports these yml files (either generated or uploaded or both) - it should also be able to handle the staging percentages, even on the UI as well.

For me, it just does not make sense to get electron-release-server to generate the yml files when electron-builder spits them out already. But that's because I am using electron-builder. 

Any thoughts?

**Comment by ArekSredzki** [comment]
Hey all, sorry for not getting to this or the other PRs. I will have more available as of tomorrow evening and will dedicate Thursday to going through all of this stuff :) 

@lazlojuly I like your idea of being able to upload the YAML file. For consistency's sake, I think that the YAML files should still be generated on the fly but the user should be able to drag & drop a YAML file onto the GUI (or upload it to an API endpoint just as well) and have the appropriate parameters imported (staging data for instance). That way all of the structured data is still stored in the DB and development for handling both features won't diverge much.

Thoughts?

**Comment by lazlojuly** [comment]
@ArekSredzki sure, storing in the DB would be more organised, however it would require DB modifications every time we need to support new column... unless we store it as JSON column

**Comment by ArekSredzki** [comment]
Sorry for the delay everyone
I'd love to get this merged in with @wontem's changes included. Would you two mind combining your contributions into one PR?

**Comment by develar** [comment]
Ping :)

**Comment by AndreD23** [comment]
Hi there! Is this updated? It will be merged at the project?

**Pull request closed without merging**
