### PR TITLE
NSIS differential updates support

### PR DESCRIPTION
**Pull request by JJ-8**
This PR will add support for NSIS differential updates for Windows. The differential updates are tested using electron-builder.

Please read the commit body of [9a441a379648842949a6cbce7280f16633e5d588](https://github.com/ArekSredzki/electron-release-server/commit/9a441a379648842949a6cbce7280f16633e5d588) to get an understanding of what is changed and why.

The hashing algorithm and encoding has changed from sha256-hex to sha512-base64 to match with electron-builder. I don't know if this will cause breaking changes to other update mechanisms. I tried to use sha256-hex, but it seems to be broken in electron-builder. Now it 100% matches the `.yml` files generated by electron-builder.

Also, I have added documentation for using NSIS differential updates and how to configure electron-builder correctly.

Relates to the following issues:
- Solves #87
- Related to #249
- Solves #225 
- Related to #196
- Related to #179

### CODE REVIEW

**Comment by DustinBrett** [comment]
Code looks good. Could there be an issue/conflict with pre-existing hashes? If nobody sees a concern I will approve/merge. Thanks for the PR!

**Comment by JJ-8** [comment]
The pre-existing hashes won't change. Only new uploads will include the sha512-base64 version.
However, I found the following cases where only sha256-hex is used and not sha512-base64:
- [electron-builder](https://github.com/electron-userland/electron-builder/blob/aa3625d5f6b719b6a7634c4c7ba0aad1ffe7d3d6/packages/app-builder-lib/src/publish/updateInfoBuilder.ts#L103)
- electron-forge: [here](https://github.com/electron-userland/electron-forge/blob/dae97c40dd2a127891dbf7fac46a14287f785888/packages/api/core/src/util/publish-state.ts#L38) and [here](https://github.com/electron-userland/electron-forge/blob/dae97c40dd2a127891dbf7fac46a14287f785888/packages/api/core/src/util/publish-state.ts#L64)

This could result in issues, but I don't know if this is also the case.
What we can try, is to not replace the sha256-hex, but only add the sha512-base64. It seems that electron-builder supports sha512-base64 [by default](https://github.com/electron-userland/electron-builder/blob/aa3625d5f6b719b6a7634c4c7ba0aad1ffe7d3d6/packages/builder-util-runtime/src/updateInfo.ts#L55), but the Windows build [could also have a sha256-hex](https://github.com/electron-userland/electron-builder/blob/aa3625d5f6b719b6a7634c4c7ba0aad1ffe7d3d6/packages/builder-util-runtime/src/updateInfo.ts#L85).
We need to store an additional sha512-base64 hash. However, I haven't looked into the database part and I have no experience with it. And it doesn't guarantee that it will both support the old format and the NSIS differential updates.

I have also fixed some documentation issues.

**Comment by DustinBrett** [comment]
Sounds good. I think we can merge this then and if trouble arises adjustments could be made. Thanks again!

**Comment by Lilleri** [comment]
Hello, i am using electron-react-boilerplate for my project, and it use electron-builder for the compliation it output a NSIS with his blockmap, i load it in the server and it works except for the differential download, when the application tries to updated itself it fails everytime and it output this.

Cannot download differentially, fallback to full download: Error: sha512 checksum mismatch

i cannot figure out a way to avoid mismatching, i think it should use sha256 as default encoding.

**Comment by JJ-8** [comment]
Hi @TokeyChan, I had a quick look at the current version of electron-builder and the code hasn't changed: https://github.com/electron-userland/electron-builder/blob/master/packages/builder-util-runtime/src/httpExecutor.ts#L440
So my advice still holds: try to convince it to use sha512 and it should work. I won't have time to figure out the sha2 header so if you really need this, you have to implement it yourself.

Best of luck!

**Pull request merged**
