### PR TITLE
Fix a bug

### PR DESCRIPTION
**Pull request by Qquanwei**
asset.fd -> fd

### CODE REVIEW

**Comment by Qquanwei** [comment]
I'm sorry but my commit is too long .

**Comment by ArekSredzki** [comment]
what?

**Comment by Qquanwei** [comment]
nothing  :)

**Comment by ArekSredzki** [comment]
Oh, okay :) I guess you were referring to the fact that you had many commits. But I squashed the PR so it wasn't an issue 👍

**Pull request merged**
