### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by dodois**

### CODE REVIEW

**Comment by ArekSredzki** [comment]
Mind adding a description stating why this is necessary or desirable?

**Comment by dodois** [comment]
> https://hub.docker.com/_/node
This image does not contain the common packages contained in the default tag and only contains the minimal packages needed to run node. Unless you are working in an environment where only the node image will be deployed and you have space constraints, we highly recommend using the default image of this repository.

**Comment by ArekSredzki** [comment]
Thanks, doesn’t that contradict your change? My interpretation of that statement is that we should not use the slim image as the default

**Comment by dodois** [comment]
You are right

**Pull request closed without merging**
